org: myselfdev97
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

package:
  individually: true

build:
  minify: true
  sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST
  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST
